// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cihwottyfupbhnblxibf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpaHdvdHR5ZnVwYmhuYmx4aWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjgzODcsImV4cCI6MjA2NTc0NDM4N30.MP8EfI0yS8LOA13sH0kq9Yc2Yyz7En32a9cFbeS0xY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);